spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3307/gestion_conges?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=OMAR0091bh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

server.port=8080

app.jwt.secret=MySuperSecretKeyForJwtGenerationMustBeLongEnough123456
app.jwt.expiration=86400000
